spring.data.mongodb.uri: mongodb+srv://${USER_DB}:${PASSWORD_DB}@webfluxcourse.ul56i.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=webfluxcourse
spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation = true
